# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-23 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('price_base_unit', models.IntegerField()),
                ('condition', models.CharField(choices=[('U', 'Unboxed'), ('UP', 'Unboxed Plus'), ('LN', 'Like New'), ('GN', 'Gently Used'), ('WU', 'Well Used')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('furniture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='furniture.Furniture')),
                ('furniture_type', models.CharField(choices=[('QS', 'Queen size beds'), ('KS', 'King Size Beds'), ('SB', 'Single Bed'), ('D', 'Diwans')], max_length=5)),
                ('material', models.CharField(choices=[('SW', 'Solid Wood'), ('PW', 'Ply Wood'), ('EW', 'Engineering Wood'), ('M', 'Metal Framed')], max_length=2)),
                ('storage', models.CharField(choices=[('BD', 'Box/Drawer Storage'), ('HS', 'Hydraulic Storage'), ('NS', 'Non-Storage')], max_length=2)),
            ],
            options={
                'es_index_name': 'f-bed-index',
                'es_type_name': 'f_bed_index',
                'es_mapping': {'properties': {'brand': {'type': 'text'}, 'condition': {'type': 'text'}, 'furniture_type': {'type': 'text'}, 'material': {'type': 'text'}, 'name': {'type': 'text'}, 'price_base_unit': {'type': 'long'}, 'storage': {'type': 'text'}}},
            },
            bases=('furniture.furniture',),
        ),
        migrations.CreateModel(
            name='Dining',
            fields=[
                ('furniture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='furniture.Furniture')),
                ('furniture_type', models.CharField(choices=[('4S', '4 Seater Sets'), ('6S', '6 Seater Sets'), ('DT', 'Dining Tables')], max_length=5)),
                ('material', models.CharField(choices=[('G', 'Glass'), ('SMW', 'Seesham/Mango Wood'), ('RPW', 'Rubber/Pine Wood'), ('TW', 'Teak Wood'), ('CB', 'Cane Bamboo')], max_length=2)),
            ],
            options={
                'es_index_name': 'f-dining-index',
                'es_type_name': 'f_dining_index',
                'es_mapping': {'properties': {'brand': {'type': 'text'}, 'condition': {'type': 'text'}, 'furniture_type': {'type': 'text'}, 'material': {'type': 'text'}, 'name': {'type': 'text'}, 'price_base_unit': {'type': 'long'}}},
            },
            bases=('furniture.furniture',),
        ),
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('furniture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='furniture.Furniture')),
                ('furniture_type', models.CharField(choices=[('S', 'One Seater'), ('SS', 'Two Seater'), ('SSS', 'Three Seater'), ('SET', 'Sofa Set'), ('LS', 'L Shaped Sofa'), ('SB', 'Sofa cum Bed'), ('R', 'Recliners')], max_length=5)),
                ('material', models.CharField(choices=[('U', 'Upholstered'), ('WF', 'Wood Framed'), ('CB', 'Cane/Bamboo'), ('MF', 'Metal Framed')], max_length=2)),
                ('softness', models.CharField(choices=[('SS', 'Super Soft'), ('S', 'Soft'), ('F', 'Firm')], max_length=2)),
            ],
            options={
                'es_index_name': 'f-sofa-index',
                'es_type_name': 'f_sofa_index',
                'es_mapping': {'properties': {'brand': {'type': 'text'}, 'condition': {'type': 'text'}, 'furniture_type': {'type': 'text'}, 'material': {'type': 'text'}, 'name': {'type': 'text'}, 'price_base_unit': {'type': 'long'}, 'softness': {'type': 'text'}}},
            },
            bases=('furniture.furniture',),
        ),
    ]
